#+TITLE: vc

* NAME

vc - A command to open and edit commands and shell functions.

* SYNOPSIS

#+begin_src shell
vc [-sLch] CMD
whence [-L] CMD
#+end_src

* DESCRIPTION

The command =vc= finds and opens commands
- shell functions,
- commands from =PATH=, and
- sourceable files from =PATH=
in that order.

In the case of shell functions, it opens the file containing the definition
of the function at the line where the function definition starts.

=vc= only looks for sourceable files if the shell option =sourcepath= is on.

=vc= searches in the same order as the shell would for results.  Therefore,
what =vc= opens is also what gets run (unless there is a shell builtin named
=CMD=.

The =whence= command follows the same logic but simply prints the location
of the shell function, command, or sourceable file.

Some handling of aliases is available if the variable =VC_EXPAND_ALIASES= is
defined and not empty.  In that case, the definition of the alias is expanded
and the first word of the definition is used for the search.

For example, if ~alias doit='cmd arg1 arg2'~ then the first word of the alias
definition is =cmd= and =vc= will look for a shell function, executable file,
or sourceable file in =PATH=.

* OPTIONS

Options =-s= and =-c= only apply to =vc=.

** ~-s~

If =CMD= is a shell function, when returning from the editor, source the file
containing its definition.  If =CMD= is not a shell function, this option
does nothing and no warning is given.

** ~-L~

Resolve all links using the =realpath= command.  Show this path in the output
and open the resolved path in the editor.

** ~-c~

Only look for executable files from PATH skipping shell functions and
aliases.

** ~-h~

Show a short help.

* CAVEATS

** Sourcing with relative paths

When doing =source FILE= defines a function =my-func=, bash remembers the
exact value of =FILE= as the location of the definition of the function.  If
=FILE= is a relative path, then =vc my-func= will only succeed if =FILE=
exists relative to =PWD=.

However, BASH 5.3 the shell option =bash_source_fullpath=.  If this option is
set, then BASH will resolve =FILE= to an absolute path.

I recommend sourcing using absolute paths in shell configuration files.

** Aliases

BASH does not remember where aliases are defined.  The best we can do is get
the first word of the alias definition and try to find a shell-function,
executable file in =PATH=, or sourceable file in =PATH= with that name.

** Non text files

Many executable files in =PATH= are compiled binaries.  Before opening a
file, =vc= runs the =file= command and if the result does not contain either
=ASCII=, =UTF-8=, or =text=, then a prompt informs the user and asks if they
still want to open the file, if you are not sure, you should answer yes
because this method of determining if the file is text is not garanteed to be
correct.

* Tips on finding alias definitions

Since the tool cannot find alias defintions, here are some tips for doing
that manually.

First set a PS4 like this:
#+begin_src
PS4='+ \033[35m${BASH_SOURCE[0]}\033[36m:\033[1;37m${FUNCNAME:+${FUNCNAME[0]}}\033[22;36m:\033[32m${LINENO}\033[36m:\033[0m' bash [--login] -x
#+end_src

If environment variables can affect the startup process, something like
#+begin_src
ssh localhost "PS4='+ \033[35m${BASH_SOURCE[0]}\033[36m:\033[1;37m${FUNCNAME:+${FUNCNAME[0]}}\033[22;36m:\033[32m${LINENO}\033[36m:\033[0m' bash [--login] -x"
#+end_src

And search the output for ~alias =~.

* LORE

I created this script when answering
[[https://stackoverflow.com/questions/54710501/command-completion-with-full-path-expansion-injected-into-history-for-vim/74283218#74283218][this question on Stack Overflow]].
That's why the command is called =vc= so I don't know what VC stands for.
But I'm deciding right now that it's for "view command".

* AUTHOR

Philippe Carphin
